// Rewrites the source mark as the app's RamblaLogo component.
//
// The mark stays theme-tinted: every fill or stroke painted in the brand colour
// becomes the `fill` the component resolved, so the `color` prop and the theme
// foreground keep working exactly as they did upstream.

const RN_TAGS = {
  circle: "Circle",
  clippath: "ClipPath",
  defs: "Defs",
  ellipse: "Ellipse",
  g: "G",
  lineargradient: "LinearGradient",
  mask: "Mask",
  path: "Path",
  polygon: "Polygon",
  polyline: "Polyline",
  radialgradient: "RadialGradient",
  rect: "Rect",
  stop: "Stop",
};

// react-native-svg takes camelCase props, except for the gradient stop
// attributes, which it spells the CSS way.
const camel = (name) =>
  name === "stop-color" || name === "stop-opacity"
    ? name
    : name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

function toJsx(markup, brand) {
  return markup
    .replace(/<(\/?)([a-zA-Z]+)([^>]*?)(\/?)>/g, (whole, close, tag, attrs, selfClose) => {
      const name = RN_TAGS[tag.toLowerCase()];
      if (!name) return whole;
      return `<${close}${name}${attrs.replace(/([a-zA-Z-]+)=/g, (_, key) => `${camel(key)}=`)}${selfClose}>`;
    })
    .replace(/(fill|stroke)="([^"]*)"/g, (whole, prop, value) =>
      value.toLowerCase() === brand.toLowerCase() ? `${prop}={fill}` : whole,
    );
}

export function componentSource(art) {
  const body = toJsx(art.inner, art.brand)
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => `      ${line}`)
    .join("\n");

  const imports = [...new Set(Object.values(RN_TAGS))]
    .filter((tag) => new RegExp(`<${tag}[\\s/>]`).test(body))
    .sort()
    .join(", ");

  return `// Generated by fork/brand/generate.mjs from fork/brand/rambla-logo.svg. Do not edit by hand.
import Svg, { ${imports} } from "react-native-svg";
import { useUnistyles } from "react-native-unistyles";

interface RamblaLogoProps {
  size?: number;
  color?: string;
}

export function RamblaLogo({ size = 64, color }: RamblaLogoProps) {
  const { theme } = useUnistyles();
  const fill = color ?? theme.colors.foreground;

  return (
    <Svg width={size} height={size} viewBox="${art.vbX} ${art.vbY} ${art.vbW} ${art.vbH}" fill="none">
${body}
    </Svg>
  );
}
`;
}
