// Generated by fork/brand/generate.mjs from fork/brand/rambla-logo.svg. Do not edit by hand.
import Svg, { Circle, G, Mask, Path, Rect } from "react-native-svg";
import { useUnistyles } from "react-native-unistyles";

interface RamblaLogoProps {
  size?: number;
  color?: string;
}

export function RamblaLogo({ size = 64, color }: RamblaLogoProps) {
  const { theme } = useUnistyles();
  const fill = color ?? theme.colors.foreground;

  return (
    <Svg width={size} height={size} viewBox="0 0 700 700" fill="none">
      <Mask id="rambla-cut" maskUnits="userSpaceOnUse" x="0" y="0" width="700" height="700">
        <Rect width="700" height="700" fill="#fff" />
        <Circle cx="435.7" cy="79.6" r="9.5" fill="#000" />
      </Mask>
      <G mask="url(#rambla-cut)">
        <Path
          d="M255 320 L255 268
      C255 184 273 126 330 94
      C394 58 472 74 499 132
      C524 184 508 252 458 286
      C449.6 290.8 438.5 295.4 426.05 298.61"
          stroke={fill}
          strokeWidth="46"
          strokeLinecap="butt"
          strokeLinejoin="round"
          fill="none"
        />
        <Path
          d="M428.3 274
      C407.4 281 363.8 283.3 347.4 268.6
      A19 19 0 0 0 320.6 295.4
      C352 326 400 336 442.9 317.6 Z"
          fill={fill}
        />
        <Path
          d="M232 300
      C232 400 235 534 209.3 630.7
      A9 9 0 0 0 226.7 635.3
      C263.1 498 278 442 278 300 Z"
          fill={fill}
        />
        <Path
          d="M466 74
      C498 64 528 58 553.1 60.8
      C556 61.5 556.5 65 553.5 66
      C534 72 512 86 492 99
      C481 90 471 82 466 74 Z"
          fill={fill}
        />
        <Path
          d="M490 124
      C517.6 111.1 533.6 107.8 558 89.5
      C561.5 88.5 562 84 558.5 82.5
      C538 87.5 516 94 492 99
      C490.5 108 490 116 490 124 Z"
          fill={fill}
        />
        <Path
          d="M347.4 268.6
      C440.9 362.1 500.4 484.1 516.5 615.3
      A9 9 0 0 1 498.6 617.5
      C470.8 495.4 409.1 383.9 320.6 295.4 Z"
          fill={fill}
        />
      </G>
    </Svg>
  );
}
