// Generated by fork/brand/generate.mjs from fork/brand/rambla-logo.svg. Do not edit by hand.
import Svg, { Circle, G, Mask, Path, Rect } from "react-native-svg";
import { useUnistyles } from "react-native-unistyles";

interface RamblaLogoProps {
  size?: number;
  color?: string;
}

export function RamblaLogo({ size = 64, color }: RamblaLogoProps) {
  const { theme } = useUnistyles();
  const fill = color ?? theme.colors.foreground;

  return (
    <Svg width={size} height={size} viewBox="0 0 700 700" fill="none">
      <Mask id="rambla-cut" maskUnits="userSpaceOnUse" x="0" y="0" width="700" height="700">
        <Rect width="700" height="700" fill="#fff" />
        <Circle cx="256" cy="204" r="13" fill="#000" />
        <Path
          d="M337 234 C402 246 443 278 464 316
      C430 293 386 272 337 261
      C326 255 328 236 337 234 Z"
          fill="#000"
        />
        <Path
          d="M337 278 C402 290 443 322 464 360
      C430 337 386 316 337 305
      C326 299 328 280 337 278 Z"
          fill="#000"
        />
        <Path
          d="M337 322 C402 334 443 366 464 404
      C430 381 386 360 337 349
      C326 343 328 324 337 322 Z"
          fill="#000"
        />
      </Mask>
      <G mask="url(#rambla-cut)" fill={fill}>
        <Path
          d="M198 600 L198 268
      C198 202 240 166 300 166
      L320 180 L306 434 L262 434 L262 600 Z"
        />
        <Path d="M204 206 L136 220 L206 248 Z" />
        <Path
          d="M300 166 C428 166 512 238 512 312
      C512 390 430 436 300 436 Z"
        />
        <Path
          d="M320 402 C412 434 508 500 574 578
      L530 616 C456 538 376 486 294 456 Z"
        />
      </G>
    </Svg>
  );
}
